name: Lint & clone repository to remote server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go version
      - name: Install dependencies
        run: go mod download
      - name: Run test
        shell: bash
        run: |
          touch .env
          echo "IMAGE_STORAGE_PATH=images" >> .env
          echo "PDF_STORAGE_PATH=pdf" >> .env
          go run main.go & pid=$!; wait $pid; go test ./...

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            whoami
            cd /critik-v
            rm -rf ./${{github.event.repository.name}}
            git clone https://github.com/${{github.repository}}.git
            cd ./${{github.event.repository.name}}
            cp .env.example .env
            sed -i "s/GIN_MODE=.*$/GIN_MODE=release/" .env
            sed -i "s/IMAGE_STORAGE_PATH=.*$/IMAGE_STORAGE_PATH=images/" .env
            sed -i "s/PDF_STORAGE_PATH=.*$/PDF_STORAGE_PATH=pdf/" .env
            sed -i "s/SERVER_SERVICE_PORT=.*$/SERVER_SERVICE_PORT=${{secrets.SERVER_PORT}}/" .env
            sed -i "s/SERVER_SERVICE=.*$/SERVER_SERVICE=${{secrets.SERVER_SERVICE}}/" .env

